"use strict";

// This file is auto-generated by refactor.js
// It acts as the main entry point, importing all modules.

import "./scripts/config.js";
import "./scripts/dom.js";
import "./scripts/data.js";
import "./scripts/utilities.js";
import "./scripts/normalization.js";
import "./scripts/calculate.js";
import "./scripts/compare.js";
import "./scripts/header-slider.js";
import "./scripts/page-scroll.js";
import "./scripts/events.js";
